//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarbonWebForms.Views.Projects {
	
	
	public partial class ProjectPage {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Deadline;
		
		protected System.Web.UI.WebControls.Repeater MemberRptr;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Description;
	}
}
