// <auto-generated />
using System;
using CashewWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashewWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191102065914_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CashewWeb.Models.Accounts", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("PicturePath")
                        .HasColumnType("longtext")
                        .HasMaxLength(5000);

                    b.Property<string>("Role")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Skills")
                        .HasColumnType("longtext")
                        .HasMaxLength(6000);

                    b.Property<string>("Theme")
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("Username", "Email");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CashewWeb.Models.OrganizationAbilities", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("InviteUser")
                        .HasColumnType("int");

                    b.Property<int>("PermissionsEditing")
                        .HasColumnType("int");

                    b.Property<int>("RemoveUser")
                        .HasColumnType("int");

                    b.HasKey("Username", "Email", "Name");

                    b.ToTable("OrganizationAbilities");
                });

            modelBuilder.Entity("CashewWeb.Models.Organizations", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Activation")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Licenses")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Name");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CashewWeb.Models.Parents", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChildId")
                        .HasColumnType("longtext");

                    b.HasKey("ParentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("CashewWeb.Models.ProjectAbilities", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("AssignmentEditing")
                        .HasColumnType("int");

                    b.Property<int>("CreateProject")
                        .HasColumnType("int");

                    b.Property<int>("ProjectEditing")
                        .HasColumnType("int");

                    b.HasKey("Username", "Email", "ProjectId");

                    b.ToTable("ProjectAbilities");
                });

            modelBuilder.Entity("CashewWeb.Models.Projects", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("TaskDeadline")
                        .HasColumnType("datetime(6)")
                        .HasMaxLength(50);

                    b.Property<string>("TaskDescription")
                        .HasColumnType("longtext")
                        .HasMaxLength(65335);

                    b.Property<string>("TaskId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CashewWeb.Models.TaskAbilities", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("TaskId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("AssignmentEditing")
                        .HasColumnType("int");

                    b.HasKey("Username", "Email", "TaskId");

                    b.ToTable("TaskAbilities");
                });

            modelBuilder.Entity("CashewWeb.Models.Tasks", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("TaskDeadline")
                        .HasColumnType("datetime(6)")
                        .HasMaxLength(50);

                    b.Property<string>("TaskDescription")
                        .HasColumnType("longtext")
                        .HasMaxLength(65335);

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
